### ISSUE TITLE
Add noto-color-emoji

### ISSUE THREAD

**Issue by danirabbit** [elementary/seed-metapackages#3] opened 2018-01-03 02:17 UTC
Now that we have color emoji support, we need a color emoji font

**Comment by danirabbit** [comment] 2018-01-10 18:29
Closing in favor of https://github.com/elementary/fonts/issues/4

**Comment by danirabbit** [comment] 2018-01-18 19:41
Reopening because this is already packaged by Ubuntu

**Comment by codygarver** [comment] 2018-01-22 14:45
Duplicate of elementary/fonts#4

**Closed as completed by codygarver** 2018-01-22 14:45 UTC
